FROM python:3.5-stretch AS build-env
WORKDIR /usr/src/app
ADD out ./out
COPY requirements.txt connector.py ./
RUN pip install --upgrade pip --upgrade setuptools && \
    pip install ./out/python/ && \
    pip install -r requirements.txt  && \
    pyinstaller connector.py
RUN echo "Installed Sensibo Connector"
RUN echo "Copying into a distroless container"
FROM gcr.io/distroless/python3
COPY --from=build-env /usr/src/app/dist /usr/src/app/dist
ENTRYPOINT ["/usr/src/app/dist/connector/connector"]