apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensibo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      component: sensibo-client
  template:
    metadata:
      labels:
        component: sensibo-client
    spec:
      containers:
        - name: sensibo-client
          image: localhost:5000/connector:dev
          ports:
            - containerPort: 5000
          env:
            - name: CONNECTORNAME
              value: sensibo
          volumeMounts:
            - name: config-volume
              mountPath: root/.config/sensibo
            - name: task-pv-storage
              mountPath: logs/
      volumes:
        - name: config-volume
          configMap:
            name: connector-config
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
